import React from "react"
import ReactDOM from "react-dom/client"

const heading = React.createElement("h1",{id: "heading",xyz:"abc"},"Namaste React!")
const heading2 = React.createElement("h2",{},"Namaste React Again!")
const child = React.createElement("div",{id: "child"},[heading, heading2])
const parent = React.createElement("div",{id: "parent"},[child])
console.log(parent)
const root = ReactDOM.createRoot(document.body)
root.render(parent)

//React.createElement("h1", {id: "heading", xyz: "abc"}, "Namaste React!") is the essintial code to create a React element.
//  It takes three arguments: the type of element (in this case, "h1"), 
// an object containing any attributes or properties for the element (in this case, {id: "heading", xyz: "abc"}),
//  and the content or children of the element (in this case, "Namaste React!").

// React is injected on for the root element and not entire page which makes it flexible to use other libraries
//  like jQuery for other parts of the page.

// React.render() is used to render a React element into the DOM. It takes two arguments:
//  the React element to be rendered and the DOM node where the element should be rendered.
//  In this case, we are rendering the "parent" React element into the "root" DOM node,
//  which is created using ReactDOM.createRoot(document.body).

// package.json is configuration file for npm that contains metadata about the project and its dependencies.

// dev dependencies are packages that are only needed during development, such as testing frameworks or build tools.
// normal dependencies are packages that are needed for the application to run in production, such as React or Express.
// package-lock.json is automatically generated by npm and contains a detailed description of the dependency tree
// for the project, including the exact versions of each package that were installed. 
// It helps ensure that the same versions of packages are installed across different environments 
// and can be used to reproduce the same build in the future.

//transitive dependencies are packages that are required by other packages.
// For example, if package A depends on package B, and package B depends on package C, 
// then package C is a transitive dependency

// a normal js file is not a module by default. To make it a module, we need to add "type": "module" in package.json file.
// In a module, we can use import and export statements to share code between files.